version: '3.9'

services:
  redis:
    image: redis:7
    container_name: kz_redis
    ports:
      - "6379:6379"

  db:
    image: postgres:15
    container_name: kz_postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
    ports:
      - "5432:5432"

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kz_bot
    depends_on:
      - db
      - redis
    env_file:
      - .env
    volumes:
      - .:/app
    command: >
      sh -c "
        ./wait-for-it.sh db:5432 --timeout=30 --strict &&
        ./wait-for-it.sh redis:6379 --timeout=30 --strict &&
        python manage.py migrate &&
        python manage.py runbot
      "
  websocket:
    build:
      context: .
      dockerfile: websocket/Dockerfile
    container_name: kz_websocket
    depends_on:
      - db
      - redis
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: >
      sh -c "
        ./wait-for-it.sh db:5432 --timeout=30 --strict &&
        ./wait-for-it.sh redis:6379 --timeout=30 --strict &&
        python websocket/main.py
      "
volumes:
  pgdata:
